# This is a basic workflow to help you get started with Actions

name: arxiv-bot

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python Env
        uses: actions/setup-python@v1
        with:
          python-version: 3.6  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install PyYAML
          pip install jinja2

      # - name: modify config
      #   run: |
      #     from ruamel import yaml
      #       with open('./config.yml', encoding="utf-8") as config_file:
      #         content = yaml.load(f, Loader=yaml.RoundTripLoader)
      #         content['mail']['password'] =  ${{ secrets.PUSHPLUS }}
      #         yaml.dump(content, config_file, Dumper=yaml.RoundTripDumper)
        
      #   shell: python 


          
      - name: run arxiv-news-letter
        run: |
          python run.py 
        
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          

          
      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.qq.com
      #     server_port: 465
      #     secure: true
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: arXiv newsletter ${{ steps.date.outputs.today }}  
      #     to: sunxin000@outlook.com
      #     from: arXiv-bot
      #     html_body: ./templates/template.html



